### ISSUE TITLE
สีข้อความในส่วนต่าง ๆ

### ISSUE THREAD

**Issue by PpGamerer** [PpGamerer/To-Do-List#20]
เปลี่ยนสีข้อความ/เลือกให้เหมาะสม

**Comment by ness816** [comment]
![a](https://github.com/PpGamerer/To-Do-List/assets/152596544/2ea28601-c28c-46f9-b8c6-aa1161327a8c)
![b](https://github.com/PpGamerer/To-Do-List/assets/152596544/b8fd13e5-b215-4bf0-aa96-36a03a93c9a5)
